name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@v3
      with:
        version: 10.x
    - name: docker lint
      run: |
        npm install
        npm run build --if-present
        npm test
    - uses: zbeekman/ShellCheck-Linter-Action@v1.0.1
      name: shell linter
    - uses: eunchurn/action-publish@v1.1.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
